### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kamel-schbock** [Fzaero/Deep-Effect-Trajectory-Prediction-in-Robot-Manipulation#3]
Hi,
I am new in generating datasets so i need some help.
In the provided datasets there are four txt files (trajectories, support-points , force trajectories , shape)
If i want to use my own datasets (for example the object is  human's hand), how can i generate something similar? 
For example is there a specific algorithm to extract support points from any shape and then i can store them in a form of a txt file? 
The same question for shape.txt ( Every image consists of a set of numbers with three channels), but what are these numbers inside shape.txt and how can i extract them?  
In terms of trajectories coordinates how can i extract them (from frames of a live video or using Kinect camera or depth sensor )? What is your method? 
force trajectories.txt seems similar to trajectories.txt with some additional numbers..
I am sorry that i ask you too many questions :) but i want to learn that..  
Thank you in advance for your cooperation and help.
Best

**Comment by Fzaero** [comment]
Hello,

Support points are very task-specific features and I'm not sure if human hands have support points. The feature should give some kind of clue about the upcoming motion of the hand. In our case, the shape of the object was giving this clue, but I'm not sure any shape related feature will give this same clue about the human's hand. Files in our dataset can be taught as follows:
* trajectories: Trajectory of object's center of mass(A bit biased,)
* trajectories_force: Trajectory of where the action is applied on the object. Similar to trajectories.
* Support points: Task-specific feature
* Shape: It is used for calculating shape context features. This is a very internal to the dataset created so probably not very useful.
* Image: There is a top-down image of objects shape.

We acquired most of our trajectories from the simulation. For our real-world task, we used a depth camera with ar tag tracking(http://wiki.ros.org/ar_track_alvar). 

I can't directly help you since I don't know your task. But I can give an example. Let's say you have a reaching task. There is a table and a goal object and task is to reach the goal object with a human hand. Some features could be the goal object's position or top-down image of the table with goal object can be distinguishable.

Hope it helps.
Best regards

**Comment by Kamel-schbock** [comment]
Hey,
Thank you for answering my questions. 
My task is to predict the trajectory or path of human's wrist using deep neural network.
I thought (i can apply your method with some extension for this purpose, if i assume a wrist is  an object). 
I try to find any helpful method to do it with computer vision as well. but maybe it is difficult.
Do you have some suggestions or ideas or papers these can help me? Or it could be possible to extend your implementation?
Best regards

**Comment by Fzaero** [comment]
Maybe you can check this paper: QuaterNet: A Quaternion-based Recurrent Model for Human Motion
(https://arxiv.org/abs/1805.06485), they also share their codes (https://github.com/facebookresearch/QuaterNet). Probably your task is simpler than one in the paper, but it may give an idea.

Best regards
